### ISSUE TITLE
atmosphere.refine_plev is not working

### ISSUE THREAD

**Issue by ClKroll** [atmtools/konrad#104]
The function atmosphere.refine_plev is returning error messages: 

> d = cls(phlev=dictionary['phlev'])

> KeyError: 'phlev'

**Comment by lkluft** [comment]
Thanks for the issue report! I am aware of the problem; actually, I already fixed it in a development branch but haven't merged it, yet. I will do so ASAP.

**Comment by lkluft** [comment]
I merged a PR (#105) that should fix the issue.
