### ISSUE TITLE
konrad.humidity.stratosphere.NoCoupling depends on konrad.humidity.FixedVMR

### ISSUE THREAD

**Issue by ClKroll** [atmtools/konrad#107]
Using konrad.humidity.stratosphere.NoCoupling can lead to counterintuitive results as e.g. the usage with FixedRH will lead to an overwriting of the "fixed" stratospheric humidity profile. It seems like the NoCoupling really depends on the FixedVMR version, which then makes the usage of NoCoupling obsolete since the WV profile is already fixed. Perhaps the NoCoupling option should be removed from the code to prevent misunderstandings? If needed the konrad.humidity.stratosphere.FixedStratosphericVMR might be expanded to allow for a height dependent SWV profile.

**Comment by SallyDa** [comment]
I think we can just get rid of  ``NoCoupling``. If we decide we need another stratospheric humidity class, we can always create it at a later time. What do you think @lkluft ?

**Comment by lkluft** [comment]
I totally agree with the two of you. The current behaviour is not intuitive, but a fix to make the `NoCoupling` work together with `FixedRH` would need some tweaking. Removing `NoCoupling` (_optional:_ and extending the `FixedVMR` class) seems like the cleanest way to go

**Comment by lkluft** [comment]
I already have a commit to refactor the extraction of relative humidity profiles from the initial atmosphere. I will bundle those in a PR later today

**Comment by SallyDa** [comment]
Sounds good, thanks :)

**Comment by ClKroll** [comment]
Thanks :-)
