### ISSUE TITLE
simotrostra and Cariolle

### ISSUE THREAD

**Issue by diegojco** [atmtools/konrad#134]
When using the Cariolle scheme I get an exception: ModuleNotFoundError: No module named 'simotrostra'. It is related to the import that is made in the __call__method of the Cariolle class. Does the module exist or is not yet implemented?

**Comment by SallyDa** [comment]
Hi Diego,
I guess you haven't installed `simotrostra` (Agatha); it's a separate package that can be found [here](https://gitlab.com/simple-stratospheric-chemistry/simotrostra). You can install it using `git clone https://gitlab...simotrostra`, going into the repository and running `python setup.py install`.
Let me know if you still have problems.
