### ISSUE TITLE
Import fails with 'ValueError: numpy.ndarray size changed'

### ISSUE THREAD

**Issue by suessspeise** [atmtools/konrad#216]
During the import of the module this error occurs:

```python
File ~/.local/lib/python3.10/site-packages/climt/_components/berger_solar_insolation.py:4
      2 import logging
      3 try:
----> 4     from ._berger_solar_insolation import get_solar_parameters, get_orbital_parameters
      5 except ImportError:
      6     logging.warning(
      7         'Import failed. Insolation is likely not compiled and will not be '
      8         'available.'
      9     )

File ~/.local/lib/python3.10/site-packages/climt/_components/_berger_solar_insolation.pyx:1, in init climt._components._berger_solar_insolation()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

See [this notebook](https://gitlab.gwdg.de/hernan.campos/warm_eurec4a/-/blob/main/lost%2Bfound/problem_konrad_import.ipynb).

**Comment by diegojco** [comment]
What process did you use for installing ``konrad``. Did you install the full ``climt`` or just ``RRTMG``?

**Comment by suessspeise** [comment]
I used `pip install konrad`. I installed neither `climt` nor `RRTMG` explicitly?
I added the output of [`pip freeze`](https://pip.pypa.io/en/stable/cli/pip_freeze/) to the notebook. `RRTMG` does not appear there, climt does.
```
climt==0.16.25
```

**Comment by lkluft** [comment]
Did you update the environment afterwards? Some parts of `climt` are very picky about the installed NumPy version which could lead to your issue in case your numpy version got updated at some point.

**Comment by suessspeise** [comment]
Setting up a new environment using the provided [`environment.yaml`](https://github.com/atmtools/konrad/blob/main/environment.yaml) solved the problem.
Sorry for the fuss and thanks for the support!
