### ISSUE TITLE
Move Cariolle data

### ISSUE THREAD

**Issue by lkluft** [atmtools/konrad#61]
Should we move the ``Cariolle_data.nc`` to ``konrad/data``?

https://github.com/atmtools/konrad/blob/d5bbc00d6e37aa00eaf6f85a8cf143356afcae4f/konrad/ozone.py#L149-L151

**Comment by SallyDa** [comment]
Yes, I didn't want to put it in it ``konrad/tutorials/data``, but we could make a new folder for it.

**Comment by SallyDa** [comment]
Done in PR #62
