### ISSUE TITLE
Convective adjustment does not work for all RH models

### ISSUE THREAD

**Issue by lkluft** [atmtools/konrad#80]
The latest version of the convective adjustment takes changes in the water vapor profile into account. For this purpose, the humidity model is called in order to calculate the water vapor distribution for the new temperature profile:
https://github.com/atmtools/konrad/blob/d1f6089c9a08aa97f2841c08d37736413e022e85/konrad/convection.py#L149-L151

This call does not pass the ``convection=`` keyword to the humidity object which can causes issues (e.g. for the ``CoupledUTH``). I am not sure what to do about this. We could pass the convective object (``self``) to the humidity. Or we could create some "dummy convection" that only contains the current convective top (``dict('convective_top_pressure'=170e2)``)?

**Comment by SallyDa** [comment]
Ah sorry I did not consider this. Perhaps it is simply easier (neater) to go back to not including water vapour changes in the convective adjustment, as now we have included it we know it is pretty insignificant. Or do you think we should include it for all runs?

**Comment by lkluft** [comment]
No problem 😉 The convective adjustment has to work for all RH models, and a rollback seems to be the easiest solution (and does not substantially change the results as you have shown). So if you are fine with reverting the changes, I would support that. I guess we should not invest time to adapt a feature, that we do not really need right now.
