### ISSUE TITLE
simple_rce tutorial broken

### ISSUE THREAD

**Issue by ClKroll** [atmtools/konrad#85]
The simple_rce tutorial seems to be broken. If the atmosphere is created from a pressure grid it works. It would be nice if you could also load the atmosphere from a netcdf file.

**Comment by lkluft** [comment]
Thanks for the bug report!

It is actually possible to load an atmosphere from a netCDF file, but the pressure grids in the distributed file are "broken"; the upper most level is 0 Pa, which seems to break the latest implementation of the convection scheme. That is the reason, why creating the atmosphere from a pressure grid with a non-zero upper-limit works.

There are two possible solutions:
1. Replace the pressure grids in the netCDF file
2. Change the example to create the atmosphere from a pressure grid (as in #86)

I prefer the second option, it feels more intuitive for beginners. Any opinions @ClKroll @SallyDa?

**Comment by SallyDa** [comment]
I'm fine with the second option. So, the new function to create pressure grids has a non zero value for both the top pressure level and the top half pressure level?

**Comment by lkluft** [comment]
Yes, the upper most half-level is set to 1 Pa by default and the full-levels are defined to be in the middle of the half-levels.

**Comment by SallyDa** [comment]
Okay, thanks.

**Comment by lkluft** [comment]
Fixed in #86
